var cursosjson = {
    "3ciclo": [
        "TEORÍA DE SISTEMAS",
        "FUNDAMENTOS DE PROGRAMACIÓN",
        "TÉCNICAS DE PROGRAMACIÓN",
        "ARQUITECTURA DE COMPUTADORAS",
        "CÁLCULO II",
        "FÍSICA I"
    ],
    "4ciclo": [
        "SISTEMAS OPERATIVOS",
        "CÁLCULO III",
        "ESTADÍSTICA Y PROBABILIDAD I",
        "FÍSICA II",
        "ESTRUCTURA DE DATOS Y ALGORITMOS",
        "ORGANIZACIÓN DE EMPRESAS"
    ],
    "5ciclo": [
        "PROGRAMACIÓN",
        "INGENIERÍA DE PROCESOS",
        "TALLER DE SISTEMAS OPERATIVOS",
        "COMUNICACIÓN DE DATOS",
        "ESTADÍSTICA Y PROBABILIDAD II"
    ],
    "6ciclo": [
        "REDES DE COMPUTADORAS",
        "INGENIERÍA DE DATOS",
        "SISTEMAS DE SOPORTE EMPRESARIAL",
        "APLICACIONES ESTADÍSTICAS EN LA EMPRESA",
        "INVESTIGACIÓN DE OPERACIONES I",
        "PROGRAMACIÓN INTERNET",
        "SEMINARIO CONECTIVIDAD CCNA"
    ],
    "7ciclo": [
        "INGENIERÍA DE SOFTWARE I",
        "SISTEMAS LOGÍSTICOS Y CADENA DE SUMINISTROS",
        "REDES INALÁMBRICAS",
        "SEGURIDAD DE REDES",
        "GESTIÓN DE PROCESOS DE NEGOCIOS",
        "DINAMICA DE SISTEMAS"        
    ],
    "8ciclo": [
        "INGENIERÍA DE SOFTWARE II",
        "ARQUITECTURA DEL DATA CENTER",
        "PLANEAMIENTO DE REDES TELEMÁTICAS",
        "PRODUCTOS DE SOFTWARE PARA LA GESTIÓN",
        "SISTEMAS DE INTELIGENCIA",
        "MARKETING"
    ],
    "9ciclo": [
        "SISTEMAS DE GESTIÓN DE OPERACIONES EMPRESARIALES",
        "ARQUITECTURA DEL SOFTWARE",
        "GESTIÓN DE SERVICIOS DE TECNOLOGÍAS DE INFORMACIÓN",
        "SEMINARIO DE TESIS I",
        "CALIDAD DE SOFTWARE Y AUDITORÍA DE SISTEMAS",
        "SISTEMA DE SOPORTE DE DECISIONES",
        "ANÁLISIS CUANTITATIVO DEL RIESGO",
        "PLANEAMIENTO ESTRATÉGICO",
        "LEGISLACIÓN Y ETICA INFORMÁTICA"
    ],
    "10ciclo": [
        "PROYECTOS DE SISTEMA DE INFORMACIÓN",
        "GESTIÓN DE PROYECTOS CAPM",
        "SEGURIDAD DE LA INFORMACIÓN",
        "ARQ.EMPRESARIAL",
        "SOLUCIONES INFORMÁTICOS DE LA CADENA DE SUMINISTROS",
        "SEMINARIO DE TESIS II",
        "GESTIÓN DE TECNOLOGÍAS DE INFORMACIÓN",
        "GESTIÓN DE RECURSOS HUMANOS"
    ]
};