var cursosjson = {
    "3ciclo": [
        "CÁLCULO II",
        "FÍSICA I",
        "FUNDAMENTOS DE PROGRAMACIÓN",
        "TÉCNICAS DE PROGRAMACIÓN",
        "TEORÍA DE SISTEMAS",
        "ARQUITECTURA DE COMPUTADORAS"
    ],
    "4ciclo": [
        "CÁLCULO III",
        "ESTADÍSTICA Y PROBABILIDAD I",
        "FÍSICA II",
        "ORGANIZACIÓN DE EMPRESAS",
        "ESTRUCTURA DE DATOS Y ALGORITMOS",
        "SISTEMAS OPERATIVOS"
    ],
    "5ciclo": [
        "ESTADÍSTICA Y PROBABILIDAD II",
        "PROGRAMACIÓN",
        "INGENIERÍA DE PROCESOS",
        "TALLER DE SISTEMAS OPERATIVOS",
        "COMUNICACIÓN DE DATOS"
    ],
    "6ciclo": [
        "INVESTIGACIÓN DE OPERACIONES I",
        "INGENIERÍA DE DATOS",
        "PROGRAMACIÓN INTERNET",
        "SISTEMAS DE SOPORTE EMPRESARIAL",
        "APLICACIONES ESTADÍSTICAS EN LA EMPRESA",
        "REDES DE COMPUTADORAS",
        "SISTEMAS OPERATIVOS PARA DISPOSITIVOS MÓVILES"
    ],
    "7ciclo": [
        "INGENIERÍA DE SOFTWARE I",
        "SISTEMAS LOGÍSTICOS Y CADENA DE SUMINISTROS",
        "REDES INALÁMBRICAS",
        "SEGURIDAD DE REDES",
        "GESTIÓN DE PROCESOS DE NEGOCIOS",
        "PROGRAMACIÓN JAVA",
        "ADMINISTRACIÓN DE BASE DE DATOS ORACLE",
        "DINAMICA DE SISTEMAS",
        "SEMINARIO DE REDES CCNA"
    ],
    "8ciclo": [
        "MARKETING",
        "INGENIERÍA DE SOFTWARE II",
        "PRODUCTOS DE SOFTWARE PARA LA GESTIÓN",
        "PLANEAMIENTO DE REDES TELEMÁTICAS",
        "ARQUITECTURA DEL DATA CENTER",
        "SISTEMAS DE INTELIGENCIA",
        "ANÁLISIS DE NEGOCIOS CON TI"
    ],
    "9ciclo": [
        "PLANEAMIENTO ESTRATÉGICO",
        "SISTEMAS DE GESTIÓN DE OPERACIONES EMPRESARIALES",
        "ARQUITECTURA DEL SOFTWARE",
        "LEGISLACIÓN Y ETICA INFORMÁTICA",
        "CALIDAD DE SOFTWARE Y AUDITORÍA DE SISTEMAS",
        "GESTIÓN DE SERVICIOS DE TECNOLOGÍAS DE INFORMACIÓN",
        "SEMINARIO DE TESIS I",
        "SISTEM. E INNOVAC.TECNOLÓGICA"
    ],
    "10ciclo": [
        "ARQ.EMPRESARIAL",
        "GESTIÓN DE TECNOLOGÍAS DE INFORMACIÓN",
        "SEMINARIO DE TESIS II",
        "PROYECTOS DE SISTEMA DE INFORMACIÓN",
        "SEGURIDAD DE LA INFORMACIÓN",
        "GESTIÓN DE RECURSOS HUMANOS",
        "GESTIÓN DE PROYECTOS CAPM"
    ]
};